### ISSUE TITLE
 限制加三条记录是不是有点死

### ISSUE THREAD

**Issue by bestZwei** [oiov/wr.do#1]
假如我申请了 v.xx.xx，那么*.v.xx.xx是不是也应该属于我；
如果要分开申请，假如我申请了 v.xx.xx，你也应该限制一下别人申请 *.v.xx.xx 的可能性。
申请了一个子域名，应该能对这个子域名和它的子域名自由添加各种记录，但是你现在只开放A和CNAME，连邮箱都用不了

**Comment by oiov** [comment]
目前只能申请三级；
邮箱暂不考虑开放

**Comment by bestZwei** [comment]
TXT记录呢，GitHub验证域名属于自己，要验证TXT记录

**Comment by oiov** [comment]
后期考虑吧
