### ISSUE TITLE
deploy with Vercel 有哪些Environment Variable 是必填的？

### ISSUE THREAD

**Issue by thinker007** [oiov/wr.do#4]
下面这些是否都是必填？

| Environment Variable          | Value                   | Description                                                  |
| :---------------------------- | :---------------------- | :----------------------------------------------------------- |
| NEXTAUTH_URL                  | `http://localhost:3000` | The URL of the Next.js application.                          |
| AUTH_SECRET                   | `123465`                | The secret used to encrypt tokens and email verification hashes. |
| DATABASE_URL                  | `file:./db.sqlite`      | The path to the postgres database.                           |
| GOOGLE_CLIENT_ID              | `123465`                | The ID of the Google OAuth client.                           |
| GOOGLE_CLIENT_SECRET          | `123465`                | The secret of the Google OAuth client.                       |
| GITHUB_ID                     | `123465`                | The ID of the GitHub OAuth client.                           |
| GITHUB_SECRET                 | `123465`                | The secret of the GitHub OAuth client.                       |
| RESEND_API_KEY                | `123465`                | The API key for Resend.                                      |
| CLOUDFLARE_ZONE_ID            | `123465`                | The zone ID for Cloudflare.                                  |
| CLOUDFLARE_API_KEY            | `123465`                | The API key for Cloudflare.                                  |
| CLOUDFLARE_EMAIL              | `123465`                | The email for Cloudflare.                                    |
| NEXT_PUBLIC_FREE_RECORD_QUOTA | `3`                     | The number of free records.                                  |
| NEXT_PUBLIC_FREE_URL_QUOTA    | `100`                   | The number of free URLs.                                     |
| NEXT_PUBLIC_OPEN_SIGNUP       | `1`                     | Open signup.                                                 |

- How to get `GOOGLE_CLIENT_ID`、`GITHUB_ID`, see [[Authentification](https://wr.do/docs/developer/authentification)](https://wr.do/docs/developer/authentification).
- How to get `RESEND_API_KEY`, see [[Email](https://wr.do/docs/developer/email)](https://wr.do/docs/developer/email).
- How to get `CLOUDFLARE_ZONE_ID`、`CLOUDFLARE_API_KEY`、`CLOUDFLARE_EMAIL`, see [[Authentification](https://wr.do/docs/developer/authentification)](https://wr.do/docs/developer/authentification).
- How to get `DATABASE_URL`, see [[Database](https://wr.do/docs/developer/database)](https://wr.do/docs/developer/database).
上面的都是必填的吗？

**Comment by oiov** [comment]
授权相关的GOOGLE_CLIENT_ID、GOOGLE_CLIENT_SECRET、GITHUB_ID、GITHUB_SECRET、RESEND_API_KEY 可以选择是否要填，但是需要改动 env.mjs 部分代码

**Comment by thinker007** [comment]
> 授权相关的GOOGLE_CLIENT_ID、GOOGLE_CLIENT_SECRET、GITHUB_ID、GITHUB_SECRET、RESEND_API_KEY 可以选择是否要填，但是需要改动 env.mjs 部分代码

建议给一个 可以跑通的 vercel 部署文档说明，目前会卡在 Environment Variable 这一步。

**Comment by Tuluobo** [comment]
> > 授权相关的GOOGLE_CLIENT_ID、GOOGLE_CLIENT_SECRET、GITHUB_ID、GITHUB_SECRET、RESEND_API_KEY 可以选择是否要填，但是需要改动 env.mjs 部分代码
> 
> 建议给一个 可以跑通的 vercel 部署文档说明，目前会卡在 Environment Variable 这一步。

按照这个填写可以运行起来：
![image](https://github.com/user-attachments/assets/36dd3f75-5cd7-4516-a44a-e1a87ec0fa12)

**Comment by oiov** [comment]
赞👍，不过不建议使用一键部署，建议在本地运行调试后再推送部署，这样可以避免一些问题。
