### ISSUE TITLE
使用GitHub和google的oauth都是提示这个

### ISSUE THREAD

**Issue by MuskZhouMQ** [oiov/wr.do#8]
Server error

There is a problem with the server configuration.

Check the server logs for more information.
同时resend的api好像也无法使用

**Comment by oiov** [comment]
本地调试 Google 和 GitHub auth 需要代理端口

**Comment by MuskZhouMQ** [comment]
不是本地调试，是不是在vercel的

**Comment by oiov** [comment]
你做了哪些操作，预期效果是什么，附上截图
